---
- hosts: routers
  roles:
    - router
- hosts: nameservers
  roles:
    - nameserver
- hosts: all
  roles:
    - network
    - firewall
    - openssh
    - ntp
    - utilities
- hosts: prometheus
  roles:
    - prometheus
