---
- hosts: routers
  roles:
    - router
- hosts: nameservers
  roles:
    - nameserver
- hosts: all
  tasks:
    # Can't reach most hosts on first run until DNS is operational, so we have
    # to check the hosts again once the nameservers are up
    - meta: clear_host_errors
- hosts: all
  roles:
    - network
    - firewall
    - openssh
    - ntp
    - system
    - utilities
- hosts: prometheus
  roles:
    - prometheus
- hosts: graylog
  roles:
    - graylog
    - nginx
