---
- name: install nameserver
  yum: name=bind
  become: yes

- name: configure nameserver
  template: src=named.conf dest=/etc/named.conf owner=named group=named validate='named-checkconf %s'
  become: yes
  notify:
    - restart nameserver

- name: configure zones
  template: src=master.zone dest=/var/named/{{ item.key }}.zone owner=named group=named validate='named-checkzone {{ item.key }} %s'
  become: yes
  with_dict: "{{ nameserver_zones }}"
  when: item.value.type == "master"
  notify:
    - restart nameserver

- name: open DNS in firewall
  firewalld: port={{ item }} state=enabled permanent=true
  with_items:
    - 53/tcp
    - 53/udp
  become: yes
  notify:
    - reload firewall

- name: start nameserver
  service: name=named state=started enabled=yes
  become: yes
