---
- name: set default gateway
  lineinfile: dest=/etc/sysconfig/network regexp="^GATEWAY=.*" line="GATEWAY={{ network_gateway }}"
  when: network_gateway is not none
  become: yes
  notify:
    - restart network

- name: unset default gateway
  replace: dest=/etc/sysconfig/network regexp="^GATEWAY=.*" replace=""
  when: network_gateway is none
  become: yes
  notify:
    - restart network

- name: configure nameservers and domain
  template: src=resolv.conf dest=/etc/resolv.conf
  become: yes
