---
- name: install syslog
  yum:
    name: syslog-ng
  become: yes

- name: configure syslog
  template:
    src: syslog-ng.conf
    dest: /etc/syslog-ng/syslog-ng.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart syslog-ng
  become: yes

- name: start syslog-ng
  systemd:
    name: syslog-ng
    state: started
    enabled: yes
  become: yes
