---
- name: configure prometheus systemd unit
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 644
  become: yes
  notify: restart prometheus

- name: create prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: 755
  become: yes

- name: configure prometheus
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: 644
  become: yes
  notify: 
    - reload prometheus

- name: open prometheus ports in firewall
  firewalld: 
    port: "{{ item }}"
    state: enabled 
    permanent: yes
    immediate: yes
  with_items:
    - 9090/tcp # Prometheus
    - 9092/tcp # Pushgateway
    - 9093/tcp # Alertmanager
  become: yes

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
  become: yes
