---
- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: yes
  become: yes

- name: restart graylog
  systemd:
    name: graylog-server
    state: restarted
    daemon_reload: yes
  become: yes
