---
- name: install docker
  yum:
    name: docker
  become: yes

- name: start docker
  service: 
    name: docker 
    state: started
    enabled: yes
  become: yes

- name: configure cadvisor systemd unit
  copy:
    src: cadvisor.service
    dest: /etc/systemd/system/cadvisor.service
    owner: root
    group: root
    mode: 644
  become: yes
  notify: restart cadvisor

- name: open cadvisor port in firewall
  firewalld:
    port: 8080/tcp
    state: enabled
    permanent: true
  become: yes
  notify:
    - reload firewall

- name: start cadvisor
  systemd:
    name: cadvisor
    state: started
  become: yes
