---
- name: restart prometheus
  systemd: 
    name: prometheus 
    state: restarted
    daemon_reload: yes
  become: yes

- name: reload prometheus
  uri: 
    url: "http://localhost:9090/-/reload"
    method: POST
